services:
  quiz-whiz-api:
    build:
      context: .
      dockerfile: api/docker/local.Dockerfile
    container_name: quiz-whiz-api
    command: "air -c air.toml"
    volumes:
      - ./api/src:/go/src/github.com/kmifa/QuizWhiz/src
      # - ./dev-support/shared/secrets/dev:/go/dev-support
    working_dir: /go/src/github.com/kmifa/QuizWhiz/src
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network1

  db:
    image: postgres:15
    container_name: quiz-whiz-db
    ports:
      - 5432:5432
    volumes:
      - quiz-whiz-db-data:/var/lib/postgresql/data
      - ./db/postgres/script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - network1

  test-db:
    image: postgres:15
    container_name: quiz-whiz-test-db
    ports:
      - 5555:5432
    volumes:
      - quiz-whiz-test-db-data:/var/lib/postgresql/data
      - ./db/postgres/script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - network1

networks:
  network1:

volumes:
  quiz-whiz-db-data:
  quiz-whiz-test-db-data:
