# golangci-lint configuration file
# see: https://github.com/golangci/golangci/wiki/Configuration

# Options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

# Settings for enabling and disabling linters
linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

# All available settings of specific linters
linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages;
    # It's a comma-separated list of prefixes
    local-prefixes: github.com/mnes/angiosuite/src

# Configuration of issue rules
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
